# Generated by Django 5.0.4 on 2024-05-09 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_rename_signup_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isAdmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='isUser',
            field=models.BooleanField(default=False),
        ),
    ]
