# Generated by Django 5.0.4 on 2024-05-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_userdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isLogin',
            field=models.BooleanField(default=False),
        ),
    ]
