# Generated by Django 5.0.4 on 2024-05-13 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_user_islogin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
