# Generated by Django 5.0.4 on 2024-05-13 18:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_delete_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('author', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='photos/%y/%m/%d')),
                ('genre', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('publisherDate', models.DateField(default=datetime.datetime.now)),
                ('ISBN', models.TextField(max_length=12)),
            ],
        ),
    ]
