# Generated by Django 5.0.4 on 2024-05-23 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_alter_book_available_alter_book_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bookId',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
