# Generated by Django 5.0.4 on 2024-05-24 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_book_bookid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDetails',
        ),
    ]
