# Generated by Django 5.0.4 on 2024-05-09 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_rename_books_book'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Signup',
            new_name='User',
        ),
    ]
