# Generated by Django 5.0.4 on 2024-05-09 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_user_islogin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='isLogin',
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isLogin', models.BooleanField(default=False)),
                ('info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.user')),
            ],
        ),
    ]
