# Generated by Django 5.0.4 on 2024-05-12 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_remove_user_islogin_userdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDetails',
        ),
    ]
