# Generated by Django 5.0.4 on 2024-05-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_alter_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(upload_to='pics/'),
        ),
    ]
