# Generated by Django 5.0.6 on 2024-05-20 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_books'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Books',
        ),
    ]
