# Generated by Django 5.0.6 on 2024-05-20 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_delete_books'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.user')),
                ('borrowed_books', models.ManyToManyField(blank=True, to='pages.book')),
            ],
            bases=('pages.user',),
        ),
    ]
