# Generated by Django 5.0.6 on 2024-05-22 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_book_borrowers_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
